# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast peak detection using sliding window
#'
#' @param positions Integer vector of genomic positions (must be sorted)
#' @param tags Numeric vector of tag counts at each position
#' @param peakDistance Integer, maximum distance for peak calling
#' @return Integer vector of peak indices (0 = not a peak, index = is a peak)
#' @export
findPeaksCpp <- function(positions, tags, peakDistance) {
    .Call('_TSSr_findPeaksCpp', PACKAGE = 'TSSr', positions, tags, peakDistance)
}

#' Fast local filtering based on peak threshold
#'
#' @param positions Integer vector of positions
#' @param tags Numeric vector of tag counts
#' @param peakIndices Integer vector of peak indices (from findPeaksCpp)
#' @param peakDistance Integer, distance for local filtering
#' @param localThreshold Numeric, threshold ratio (e.g., 0.02)
#' @param strand Character, "+" or "-" for strand direction
#' @return Logical vector indicating which positions to keep (TRUE = keep)
#' @export
localFilterCpp <- function(positions, tags, peakIndices, peakDistance, localThreshold, strand) {
    .Call('_TSSr_localFilterCpp', PACKAGE = 'TSSr', positions, tags, peakIndices, peakDistance, localThreshold, strand)
}

#' Fast quantile calculation using cumulative sum
#'
#' @param positions Integer vector of positions (sorted)
#' @param tags Numeric vector of tag counts
#' @param quantile Numeric, quantile to calculate (e.g., 0.1)
#' @param from_end Logical, calculate from end (for upper quantile)
#' @return Integer, position at the quantile
#' @export
calculateQuantilePositionCpp <- function(positions, tags, quantile, from_end = FALSE) {
    .Call('_TSSr_calculateQuantilePositionCpp', PACKAGE = 'TSSr', positions, tags, quantile, from_end)
}

#' Calculate cluster quantiles efficiently
#'
#' @param positions Integer vector of positions
#' @param tags Numeric vector of tags
#' @param cluster_starts Integer vector of cluster start indices
#' @param cluster_ends Integer vector of cluster end indices
#' @return DataFrame with q_0.1, q_0.9, and interquantile_width
#' @export
calculateClusterQuantilesCpp <- function(positions, tags, cluster_starts, cluster_ends) {
    .Call('_TSSr_calculateClusterQuantilesCpp', PACKAGE = 'TSSr', positions, tags, cluster_starts, cluster_ends)
}

#' Test function to compare R and C++ implementations
#'
#' @param n Integer, number of test positions
#' @return List with test data
#' @export
generateTestData <- function(n = 10000L) {
    .Call('_TSSr_generateTestData', PACKAGE = 'TSSr', n)
}

